### ISSUE TITLE
Update to newer QT version (6 or upper)

### ISSUE THREAD

**Issue by Zeioth** [OpenPrinting/hplip-printer-app#6]
Versions under QT6 don't behave correctly under wayland based distribution when QT_SCALE it set, which is necessary for HiDPI displays.

Specifically, dropdown menus don't detect the mouse correctly. This is a known bug of ~qt5.

**Comment by tillkamppeter** [comment]
Note that the **HPLIP Printer Application** only uses the printer drivers of HPLIP, not any of its GUI tools. The only user interface of the Printer Application is the web interface and if there show HiDPI problems it is most probably a bug of your browser.

You probably mean **HPLIP** itself, installed from source or via the distro's classic packaging method (DEB, RPM, ...). For this, please report bugs or feature requests upstream on [Launchpad](https://bugs.launchpad.net/hplip/+filebug).

**Comment by tillkamppeter** [comment]
This GUI is the `hp-toolbox` not part of the current HPLIP Printer Application. Closing ...
